SET search_path = public;

CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('admin','student')), name TEXT NOT NULL, email TEXT UNIQUE, phone TEXT UNIQUE, password_hash TEXT, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','pending','inactive')), avatar TEXT NOT NULL DEFAULT '', interests TEXT NOT NULL DEFAULT '[]', onboarding INTEGER NOT NULL DEFAULT 0, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, last_active BIGINT);
CREATE TABLE IF NOT EXISTS platform_owner (id INTEGER PRIMARY KEY CHECK(id=1), user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT UNIQUE NOT NULL, csrf TEXT NOT NULL, expires_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS otps (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, code_hash TEXT NOT NULL, purpose TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, consumed INTEGER NOT NULL DEFAULT 0, expires_at BIGINT NOT NULL, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (id TEXT PRIMARY KEY, hits INTEGER NOT NULL, expires_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS content (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('subject','chapter','topic','video')), parent_id TEXT REFERENCES content(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', thumbnail TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published')), public INTEGER NOT NULL DEFAULT 0, duration INTEGER NOT NULL DEFAULT 0, tags TEXT NOT NULL DEFAULT '[]', notes TEXT NOT NULL DEFAULT '', storage_key TEXT NOT NULL DEFAULT '', caption_key TEXT NOT NULL DEFAULT '', resource_key TEXT NOT NULL DEFAULT '', publish_at BIGINT, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS student_groups (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT NOT NULL DEFAULT '', created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS group_members (id TEXT PRIMARY KEY, group_id TEXT NOT NULL REFERENCES student_groups(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, UNIQUE(group_id,user_id));
CREATE TABLE IF NOT EXISTS access_grants (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id) ON DELETE CASCADE, group_id TEXT REFERENCES student_groups(id) ON DELETE CASCADE, content_id TEXT NOT NULL REFERENCES content(id) ON DELETE CASCADE, status TEXT NOT NULL CHECK(status IN ('assigned','revoked')), created_at BIGINT NOT NULL, CHECK((user_id IS NOT NULL AND group_id IS NULL) OR (user_id IS NULL AND group_id IS NOT NULL)));
CREATE TABLE IF NOT EXISTS progress (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, video_id TEXT NOT NULL REFERENCES content(id) ON DELETE CASCADE, position REAL NOT NULL DEFAULT 0, watched_seconds REAL NOT NULL DEFAULT 0, completed INTEGER NOT NULL DEFAULT 0, updated_at BIGINT NOT NULL, UNIQUE(user_id,video_id));
CREATE TABLE IF NOT EXISTS watch_events (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, video_id TEXT NOT NULL REFERENCES content(id) ON DELETE CASCADE, seconds REAL NOT NULL DEFAULT 0, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS announcements (id TEXT PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS notification_reads (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, announcement_id TEXT NOT NULL REFERENCES announcements(id) ON DELETE CASCADE, UNIQUE(user_id,announcement_id));
CREATE TABLE IF NOT EXISTS activity_logs (id TEXT PRIMARY KEY, actor_id TEXT, action TEXT NOT NULL, target_id TEXT, detail TEXT NOT NULL DEFAULT '', created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (id TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS uploads (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), storage_key TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, mime TEXT NOT NULL, size BIGINT NOT NULL, state TEXT NOT NULL, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS learning_assignments (id TEXT PRIMARY KEY, teacher_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', quiz_url TEXT NOT NULL DEFAULT '', due_at BIGINT NOT NULL, time_limit_minutes INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published')), created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS assignment_targets (id TEXT PRIMARY KEY, assignment_id TEXT NOT NULL REFERENCES learning_assignments(id) ON DELETE CASCADE, user_id TEXT REFERENCES users(id) ON DELETE CASCADE, group_id TEXT REFERENCES student_groups(id) ON DELETE CASCADE, CHECK((user_id IS NOT NULL AND group_id IS NULL) OR (user_id IS NULL AND group_id IS NOT NULL)));
CREATE TABLE IF NOT EXISTS assignment_resources (id TEXT PRIMARY KEY, assignment_id TEXT NOT NULL REFERENCES learning_assignments(id) ON DELETE CASCADE, upload_id TEXT NOT NULL REFERENCES uploads(id) ON DELETE CASCADE, UNIQUE(assignment_id,upload_id));
CREATE TABLE IF NOT EXISTS assignment_submissions (id TEXT PRIMARY KEY, assignment_id TEXT NOT NULL REFERENCES learning_assignments(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, started_at BIGINT NOT NULL, submitted_at BIGINT, status TEXT NOT NULL DEFAULT 'in_progress' CHECK(status IN ('in_progress','submitted','reviewed')), note TEXT NOT NULL DEFAULT '', feedback TEXT NOT NULL DEFAULT '', updated_at BIGINT NOT NULL, UNIQUE(assignment_id,user_id));
CREATE TABLE IF NOT EXISTS submission_files (id TEXT PRIMARY KEY, submission_id TEXT NOT NULL REFERENCES assignment_submissions(id) ON DELETE CASCADE, upload_id TEXT NOT NULL REFERENCES uploads(id) ON DELETE CASCADE, UNIQUE(submission_id,upload_id));
CREATE TABLE IF NOT EXISTS contacts (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, message TEXT NOT NULL, created_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_content_parent ON content(parent_id);
CREATE INDEX IF NOT EXISTS idx_access_user ON access_grants(user_id,content_id);
CREATE INDEX IF NOT EXISTS idx_access_group ON access_grants(group_id,content_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_student_grant ON access_grants(user_id,content_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_group_grant ON access_grants(group_id,content_id) WHERE group_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_group_user ON group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_progress_user ON progress(user_id);
CREATE INDEX IF NOT EXISTS idx_watch_time ON watch_events(created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_otp_identifier ON otps(identifier,created_at);
CREATE INDEX IF NOT EXISTS idx_content_status ON content(kind,status);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role,created_at);
CREATE INDEX IF NOT EXISTS idx_assignment_due ON learning_assignments(status,due_at);
CREATE INDEX IF NOT EXISTS idx_assignment_target_user ON assignment_targets(user_id,assignment_id);
CREATE INDEX IF NOT EXISTS idx_assignment_target_group ON assignment_targets(group_id,assignment_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_assignment_student_target ON assignment_targets(assignment_id,user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_assignment_group_target ON assignment_targets(assignment_id,group_id) WHERE group_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_submission_student ON assignment_submissions(user_id,assignment_id);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.users FROM anon, authenticated;
ALTER TABLE public.platform_owner ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.platform_owner FROM anon, authenticated;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sessions FROM anon, authenticated;
ALTER TABLE public.otps ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.otps FROM anon, authenticated;
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.rate_limits FROM anon, authenticated;
ALTER TABLE public.content ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.content FROM anon, authenticated;
ALTER TABLE public.student_groups ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.student_groups FROM anon, authenticated;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.group_members FROM anon, authenticated;
ALTER TABLE public.access_grants ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.access_grants FROM anon, authenticated;
ALTER TABLE public.progress ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.progress FROM anon, authenticated;
ALTER TABLE public.watch_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.watch_events FROM anon, authenticated;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.announcements FROM anon, authenticated;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.notification_reads FROM anon, authenticated;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.activity_logs FROM anon, authenticated;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.settings FROM anon, authenticated;
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.uploads FROM anon, authenticated;
ALTER TABLE public.learning_assignments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.learning_assignments FROM anon, authenticated;
ALTER TABLE public.assignment_targets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.assignment_targets FROM anon, authenticated;
ALTER TABLE public.assignment_resources ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.assignment_resources FROM anon, authenticated;
ALTER TABLE public.assignment_submissions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.assignment_submissions FROM anon, authenticated;
ALTER TABLE public.submission_files ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.submission_files FROM anon, authenticated;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.contacts FROM anon, authenticated;
