CREATE ROLE english_tech_server NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT USAGE ON SCHEMA public TO english_tech_server;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO english_tech_server;
CREATE POLICY server_access ON public.users FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.platform_owner TO english_tech_server;
CREATE POLICY server_access ON public.platform_owner FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessions TO english_tech_server;
CREATE POLICY server_access ON public.sessions FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.otps TO english_tech_server;
CREATE POLICY server_access ON public.otps FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rate_limits TO english_tech_server;
CREATE POLICY server_access ON public.rate_limits FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.content TO english_tech_server;
CREATE POLICY server_access ON public.content FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.student_groups TO english_tech_server;
CREATE POLICY server_access ON public.student_groups FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.group_members TO english_tech_server;
CREATE POLICY server_access ON public.group_members FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.access_grants TO english_tech_server;
CREATE POLICY server_access ON public.access_grants FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.progress TO english_tech_server;
CREATE POLICY server_access ON public.progress FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.watch_events TO english_tech_server;
CREATE POLICY server_access ON public.watch_events FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.announcements TO english_tech_server;
CREATE POLICY server_access ON public.announcements FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notification_reads TO english_tech_server;
CREATE POLICY server_access ON public.notification_reads FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activity_logs TO english_tech_server;
CREATE POLICY server_access ON public.activity_logs FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.settings TO english_tech_server;
CREATE POLICY server_access ON public.settings FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.uploads TO english_tech_server;
CREATE POLICY server_access ON public.uploads FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contacts TO english_tech_server;
CREATE POLICY server_access ON public.contacts FOR ALL TO english_tech_server USING (true) WITH CHECK (true);
